"""empty message

Revision ID: 224e1e945918
Revises: d69e6d739ef0
Create Date: 2020-01-14 12:30:38.008792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '224e1e945918'
down_revision = 'd69e6d739ef0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password_code', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'password_code')
    # ### end Alembic commands ###
