"""empty message

Revision ID: 2fbaef41ff4d
Revises: 120792afb90d
Create Date: 2019-12-05 13:57:04.721659

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2fbaef41ff4d'
down_revision = '120792afb90d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_description', sa.Text(), nullable=True),
    sa.Column('about_intro', sa.String(), nullable=True),
    sa.Column('about_description', sa.Text(), nullable=True),
    sa.Column('first_card_title', sa.String(), nullable=True),
    sa.Column('first_card_description', sa.Text(), nullable=True),
    sa.Column('second_card_title', sa.String(), nullable=True),
    sa.Column('second_card_description', sa.Text(), nullable=True),
    sa.Column('third_card_title', sa.String(), nullable=True),
    sa.Column('third_card_description', sa.Text(), nullable=True),
    sa.Column('blog_intro', sa.String(), nullable=True),
    sa.Column('blog_title', sa.Text(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_edited'), 'home', ['edited'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_home_edited'), table_name='home')
    op.drop_table('home')
    # ### end Alembic commands ###
