"""empty message

Revision ID: 4c9c15c00377
Revises: 2d5a2b624878
Create Date: 2019-12-09 12:26:50.559904

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c9c15c00377'
down_revision = '2d5a2b624878'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_thank_you',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_thank_you_edited'), 'contact_thank_you', ['edited'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_thank_you_edited'), table_name='contact_thank_you')
    op.drop_table('contact_thank_you')
    # ### end Alembic commands ###
