"""empty message

Revision ID: 5f6f0f22c3fb
Revises: 
Create Date: 2020-05-04 16:39:44.435538

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f6f0f22c3fb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_description', sa.Text(), nullable=True),
    sa.Column('red_intro', sa.String(), nullable=True),
    sa.Column('black_intro', sa.String(), nullable=True),
    sa.Column('intro_description', sa.Text(), nullable=True),
    sa.Column('first_offer', sa.String(), nullable=True),
    sa.Column('first_offer_description', sa.Text(), nullable=True),
    sa.Column('second_offer', sa.String(), nullable=True),
    sa.Column('second_offer_description', sa.Text(), nullable=True),
    sa.Column('third_offer', sa.String(), nullable=True),
    sa.Column('third_offer_description', sa.Text(), nullable=True),
    sa.Column('first_step', sa.String(), nullable=True),
    sa.Column('first_step_description', sa.Text(), nullable=True),
    sa.Column('second_step', sa.String(), nullable=True),
    sa.Column('second_step_description', sa.Text(), nullable=True),
    sa.Column('third_step', sa.String(), nullable=True),
    sa.Column('third_step_description', sa.Text(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_about_edited'), 'about', ['edited'], unique=False)
    op.create_table('contact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('sub_title', sa.Text(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_edited'), 'contact', ['edited'], unique=False)
    op.create_table('contact_thank_you',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_thank_you_edited'), 'contact_thank_you', ['edited'], unique=False)
    op.create_table('home',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('title_description', sa.Text(), nullable=True),
    sa.Column('about_intro', sa.String(), nullable=True),
    sa.Column('about_description', sa.Text(), nullable=True),
    sa.Column('first_card_title', sa.String(), nullable=True),
    sa.Column('first_card_description', sa.Text(), nullable=True),
    sa.Column('second_card_title', sa.String(), nullable=True),
    sa.Column('second_card_description', sa.Text(), nullable=True),
    sa.Column('third_card_title', sa.String(), nullable=True),
    sa.Column('third_card_description', sa.Text(), nullable=True),
    sa.Column('blog_intro', sa.String(), nullable=True),
    sa.Column('blog_title', sa.Text(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_edited'), 'home', ['edited'], unique=False)
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=30), nullable=False),
    sa.Column('description', sa.String(length=300), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('universal_page',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Unicode(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password', sa.String(length=128), nullable=True),
    sa.Column('about_me', sa.String(length=10000), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('firstname', sa.String(length=50), nullable=True),
    sa.Column('lastname', sa.String(length=50), nullable=True),
    sa.Column('password_code', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('block_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_blockquote', sa.Integer(), nullable=True),
    sa.Column('blockquote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockquote_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_quote_with_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_text', sa.Text(), nullable=False),
    sa.Column('paragraph_text', sa.Text(), nullable=False),
    sa.Column('order_blockquotewithheader', sa.Integer(), nullable=True),
    sa.Column('blockquotewithheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockquotewithheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('order_faq', sa.Integer(), nullable=True),
    sa.Column('faq_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faq_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grey_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_greyheader', sa.Integer(), nullable=False),
    sa.Column('greyheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['greyheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('intro', sa.String(length=200), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('user_name', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_name'], ['user.username'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_post_timestamp'), 'post', ['timestamp'], unique=False)
    op.create_table('small_grey_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_smallgreyheader', sa.Integer(), nullable=True),
    sa.Column('smallgreyheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['smallgreyheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('three_columns_with_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_no_1_header', sa.String(), nullable=False),
    sa.Column('column_no_1_text', sa.Text(), nullable=False),
    sa.Column('column_no_2_header', sa.String(), nullable=False),
    sa.Column('column_no_2_text', sa.Text(), nullable=False),
    sa.Column('column_no_3_header', sa.String(), nullable=False),
    sa.Column('column_no_3_text', sa.Text(), nullable=False),
    sa.Column('order_threecolumnswithheaders', sa.Integer(), nullable=True),
    sa.Column('threecolumnswithheaders_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threecolumnswithheaders_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users_roles',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('white_header_with_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_text', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('button_url', sa.String(), nullable=False),
    sa.Column('order_whiteheaderwithbutton', sa.Integer(), nullable=True),
    sa.Column('whiteheaderwithbutton_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['whiteheaderwithbutton_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('white_header_with_button')
    op.drop_table('users_roles')
    op.drop_table('three_columns_with_headers')
    op.drop_table('small_grey_header')
    op.drop_index(op.f('ix_post_timestamp'), table_name='post')
    op.drop_table('post')
    op.drop_table('grey_header')
    op.drop_table('faq')
    op.drop_table('block_quote_with_header')
    op.drop_table('block_quote')
    op.drop_table('user')
    op.drop_table('universal_page')
    op.drop_table('role')
    op.drop_index(op.f('ix_home_edited'), table_name='home')
    op.drop_table('home')
    op.drop_index(op.f('ix_contact_thank_you_edited'), table_name='contact_thank_you')
    op.drop_table('contact_thank_you')
    op.drop_index(op.f('ix_contact_edited'), table_name='contact')
    op.drop_table('contact')
    op.drop_index(op.f('ix_about_edited'), table_name='about')
    op.drop_table('about')
    # ### end Alembic commands ###
