"""empty message

Revision ID: 6020b8a5f2ec
Revises: 282236175629
Create Date: 2019-12-10 16:10:39.499127

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6020b8a5f2ec'
down_revision = '282236175629'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universal_page',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Unicode(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('block_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_BlockQuote', sa.Integer(), nullable=True),
    sa.Column('blockquote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockquote_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_quote_with_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_text', sa.Text(), nullable=False),
    sa.Column('paragraph_text', sa.Text(), nullable=False),
    sa.Column('order_BlockQuoteWithHeader', sa.Integer(), nullable=True),
    sa.Column('blockquotewithheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockquotewithheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('order_Faq', sa.Integer(), nullable=True),
    sa.Column('faq_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faq_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grey_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_GreyHeader', sa.Integer(), nullable=False),
    sa.Column('greyheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['greyheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('small_grey_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_SmallGreyHeader', sa.Integer(), nullable=True),
    sa.Column('smallgreyheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['smallgreyheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('three_columns_with_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_no_1_header', sa.String(), nullable=False),
    sa.Column('column_no_1_text', sa.Text(), nullable=False),
    sa.Column('column_no_2_header', sa.String(), nullable=False),
    sa.Column('column_no_2_text', sa.Text(), nullable=False),
    sa.Column('column_no_3_header', sa.String(), nullable=False),
    sa.Column('column_no_3_text', sa.Text(), nullable=False),
    sa.Column('order_ThreeColumnsWithHeaders', sa.Integer(), nullable=True),
    sa.Column('threecolumnswithheaders_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threecolumnswithheaders_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('white_header_with_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_text', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('button_url', sa.String(), nullable=False),
    sa.Column('order_WhiteHeaderWithButton', sa.Integer(), nullable=True),
    sa.Column('universal_page_whiteheaderwithbutton_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['universal_page_whiteheaderwithbutton_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('white_header_with_button')
    op.drop_table('three_columns_with_headers')
    op.drop_table('small_grey_header')
    op.drop_table('grey_header')
    op.drop_table('faq')
    op.drop_table('block_quote_with_header')
    op.drop_table('block_quote')
    op.drop_table('universal_page')
    # ### end Alembic commands ###
