"""empty message

Revision ID: 93c50b06a0f1
Revises: a6ae4dcad533
Create Date: 2019-12-06 11:30:43.321372

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '93c50b06a0f1'
down_revision = 'a6ae4dcad533'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_thank_you',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('intro', sa.String(), nullable=True),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_contact_thank_you_edited'), 'contact_thank_you', ['edited'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_contact_thank_you_edited'), table_name='contact_thank_you')
    op.drop_table('contact_thank_you')
    # ### end Alembic commands ###
