"""empty message

Revision ID: f008d50bf3e9
Revises: c68c9010767e
Create Date: 2019-12-11 13:42:22.527959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f008d50bf3e9'
down_revision = 'c68c9010767e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('universal_page',
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('url', sa.Unicode(length=20), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_table('block_quote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_blockquote', sa.Integer(), nullable=True),
    sa.Column('blockquote_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockquote_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('block_quote_with_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_text', sa.Text(), nullable=False),
    sa.Column('paragraph_text', sa.Text(), nullable=False),
    sa.Column('order_blockquotewithheader', sa.Integer(), nullable=True),
    sa.Column('blockquotewithheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['blockquotewithheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faq',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question', sa.String(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('order_faq', sa.Integer(), nullable=True),
    sa.Column('faq_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['faq_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grey_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_greyheader', sa.Integer(), nullable=False),
    sa.Column('greyheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['greyheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('small_grey_header',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header', sa.String(), nullable=False),
    sa.Column('order_smallgreyheader', sa.Integer(), nullable=True),
    sa.Column('smallgreyheader_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['smallgreyheader_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('three_columns_with_headers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('column_no_1_header', sa.String(), nullable=False),
    sa.Column('column_no_1_text', sa.Text(), nullable=False),
    sa.Column('column_no_2_header', sa.String(), nullable=False),
    sa.Column('column_no_2_text', sa.Text(), nullable=False),
    sa.Column('column_no_3_header', sa.String(), nullable=False),
    sa.Column('column_no_3_text', sa.Text(), nullable=False),
    sa.Column('order_threecolumnswithheaders', sa.Integer(), nullable=True),
    sa.Column('threecolumnswithheaders_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['threecolumnswithheaders_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('white_header_with_button',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('header_text', sa.String(), nullable=False),
    sa.Column('button_text', sa.String(), nullable=False),
    sa.Column('button_url', sa.String(), nullable=False),
    sa.Column('order_whiteheaderwithbutton', sa.Integer(), nullable=True),
    sa.Column('whiteheaderwithbutton_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['whiteheaderwithbutton_id'], ['universal_page.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('white_header_with_button')
    op.drop_table('three_columns_with_headers')
    op.drop_table('small_grey_header')
    op.drop_table('grey_header')
    op.drop_table('faq')
    op.drop_table('block_quote_with_header')
    op.drop_table('block_quote')
    op.drop_table('universal_page')
    # ### end Alembic commands ###
